avaamo_backend_rails/config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :attachments
  resources :topics
  resources :users
  get '/topics/search/all-subjects', to: 'topics#all_subjects'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

avaamo_backend_rails/app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable, polymorphic: true
end

avaamo_backend_rails/app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to @attachment, notice: 'Attachment was successfully created.' }
        format.json { render :show, status: :created, location: @attachment }
      else
        format.html { render :new }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to @attachment, notice: 'Attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @attachment }
      else
        format.html { render :edit }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to attachments_url, notice: 'Attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attachment_params
      params.require(:attachment).permit(:file_name, :file_url, :attachableable_id, :attachableable_type)
    end
end

avaamo_backend_rails/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

avaamo_backend_rails/app/views/attachments/_form.html.erb
<%= form_with(model: attachment, local: true) do |form| %>
  <% if attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>

      <ul>
        <% attachment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :file_name %>
    <%= form.text_field :file_name %>
  </div>

  <div class="field">
    <%= form.label :file_url %>
    <%= form.text_field :file_url %>
  </div>

  <div class="field">
    <%= form.label :attachableable_id %>
    <%= form.text_field :attachableable_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

avaamo_backend_rails/app/views/attachments/edit.html.erb
<h1>Editing Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Show', @attachment %> |
<%= link_to 'Back', attachments_path %>

avaamo_backend_rails/app/views/attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attachments</h1>

<table>
  <thead>
    <tr>
      <th>File name</th>
      <th>File url</th>
      <th>Attachableable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attachments.each do |attachment| %>
      <tr>
        <td><%= attachment.file_name %></td>
        <td><%= attachment.file_url %></td>
        <td><%= attachment.attachableable_id %></td>
        <td><%= link_to 'Show', attachment %></td>
        <td><%= link_to 'Edit', edit_attachment_path(attachment) %></td>
        <td><%= link_to 'Destroy', attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attachment', new_attachment_path %>

avaamo_backend_rails/app/views/attachments/new.html.erb
<h1>New Attachment</h1>

<%= render 'form', attachment: @attachment %>

<%= link_to 'Back', attachments_path %>

avaamo_backend_rails/app/views/attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File name:</strong>
  <%= @attachment.file_name %>
</p>

<p>
  <strong>File url:</strong>
  <%= @attachment.file_url %>
</p>

<p>
  <strong>Attachableable:</strong>
  <%= @attachment.attachableable_id %>
</p>

<%= link_to 'Edit', edit_attachment_path(@attachment) %> |
<%= link_to 'Back', attachments_path %>